Made it insist both prealis have same pixel size

diff --git a/scripts/transferfid b/scripts/transferfid
--- a/scripts/transferfid
+++ b/scripts/transferfid
@@ -9,6 +9,12 @@
 #  $Revision$
 #
 #  $Log$
+#  Revision 3.17  2004/07/22 18:16:45  mast
+#  Change to better sed command for stripping Ctrl M
+#
+#  Revision 3.16  2004/07/08 22:54:18  mast
+#  Switched some echos to \echo to dodge Cygwin tcsh bug
+#
 #  Revision 3.15  2004/06/29 03:50:14  mast
 #  Added nohup
 #
@@ -269,7 +275,7 @@ endif
 if ($imagea == "") then
     @ topline  = `vmstocsh < track$src.com | awk '/beadtrack/{print NR}'`
     @ nextline = $topline + $BEADTRACK_INPUTFILE_LINE
-    set imagea = `vmstocsh < track$src.com | awk '{if (NR==LINE) print}' LINE=$nextline | sed '/[^ -z]/s///g'`
+    set imagea = `vmstocsh < track$src.com | awk '{if (NR==LINE) print}' LINE=$nextline | sed '/[[:cntrl:]]/s///g'`
 endif
 
 if (! -e $imagea) then
@@ -280,7 +286,7 @@ endif
 if ($imageb == "") then
     @ topline  = `vmstocsh < track$dst.com | awk '/beadtrack/{print NR}'`
     @ nextline = $topline + $BEADTRACK_INPUTFILE_LINE
-    set imageb = `vmstocsh < track$dst.com | awk '{if (NR==LINE) print}' LINE=$nextline | sed '/[^ -z]/s///g'`
+    set imageb = `vmstocsh < track$dst.com | awk '{if (NR==LINE) print}' LINE=$nextline | sed '/[[:cntrl:]]/s///g'`
 endif
 
 if (! -e $imageb) then
@@ -335,14 +341,37 @@ endif
 # Get image sizes
 #
 set nxyz =  `header $imagea | sed -n '/rows, sections/p'| awk '{print $7, $8, $9}'`
+if ($#nxyz < 3) then
+    echo "ERROR: $pn - reading image size from header of $imagea"
+    exit 1
+endif
 @ nxa = $nxyz[1]
 @ nya = $nxyz[2]
 @ nza = $nxyz[3]
 
 set nxyz =  `header $imageb | sed -n '/rows, sections/p'| awk '{print $7, $8, $9}'`
+if ($#nxyz < 3) then
+    echo "ERROR: $pn - reading image size from header of $imageb"
+    exit 1
+endif
 @ nxb = $nxyz[1]
 @ nyb = $nxyz[2]
 @ nzb = $nxyz[3]
+
+#
+# Check pixel size
+#
+set pixela = `header $imagea | sed -n '/Pixel spacing.*\.\./s///p'`
+set pixelb = `header $imageb | sed -n '/Pixel spacing.*\.\./s///p'`
+if ($#pixela < 1 || $#pixelb < 1) then
+    echo "ERROR: $pn - reading pixel size from image file headers"
+    exit 1
+endif
+if ($pixela[1] != $pixelb[1]) then
+    echo "ERROR: $pn - pixel sizes do not match:"
+    echo "  $imagea = $pixela[1], $imageb = $pixelb[1]"
+    exit 1
+endif
 
 #
 # Set the number of reductions by 2 needed to get image size to 512 or less
@@ -666,10 +695,10 @@ endif
 if ($radius == "") then
     @ topline  = `vmstocsh < tracka.com | awk '/beadtrack/{print NR}'`
     @ reshootline = $topline + $BEADTRACK_RESHOOT_LINE
-    set reshoots = `vmstocsh < tracka.com | awk '{if (NR==LINE) print}' LINE=$reshootline | sed '/[^ -z]/s///g'`
+    set reshoots = `vmstocsh < tracka.com | awk '{if (NR==LINE) print}' LINE=$reshootline | sed '/[[:cntrl:]]/s///g'`
     @ reshootnum = $reshoots[1]
     @ radline = $topline + $BEADTRACK_RADIUS_LINE + $reshootnum
-    set radiusdark = `vmstocsh < tracka.com | awk '{if (NR==LINE) print}' LINE=$radline | sed '/[^ -z]/s///g'`
+    set radiusdark = `vmstocsh < tracka.com | awk '{if (NR==LINE) print}' LINE=$radline | sed '/[[:cntrl:]]/s///g'`
 else
     set radiusdark = $radius,$lightdark
 endif
